name: AppScan CodeSweep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AppScan CodeSweep
        uses: IBM/AppScanCodeSweep-GitHubAction@v1 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
