name: Lint Code Base

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  superlinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          RUN_LOCAL: true
